### ISSUE TITLE
找不到后端？只开源前端吗？

### ISSUE THREAD

**Issue by zhuxijing123** [alixiaodi/ss-tutor-mobile#1]
找不到后端？只开源前端吗？

**Comment by alixiaodi** [comment]
后端代码还在完善，可以先使用线上的
完善后会逐步发布







------------------ 原始邮件 ------------------
发件人: zhuxijing123 ***@***.***&gt;
发送时间: 2024年12月9日 18:15
收件人: alixiaodi/ss-tutor-mobile ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [alixiaodi/ss-tutor-mobile] 找不到后端？只开源前端吗？ (Issue #1)

**Comment by alixiaodi** [comment]
百分百真开源，不做假来源





------------------ 原始邮件 ------------------
发件人: zhuxijing123 ***@***.***&gt;
发送时间: 2024年12月9日 18:15
收件人: alixiaodi/ss-tutor-mobile ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [alixiaodi/ss-tutor-mobile] 找不到后端？只开源前端吗？ (Issue #1)





 
找不到后端？只开源前端吗？

**Comment by alixiaodi** [comment]
后台代码已经开源，请留意文档
